version: "3.8"
services:
  web:
    build: ./
    restart: always
    environment:
      - TZ=Europe/Berlin
    networks:
      - backend
    ports:
      - 7000:80
    volumes:
      - .:/var/www
    depends_on:
      - db
  db:
    image: mariadb:10.5.21
    restart: always
    networks:
      - backend
    ports:
      - 127.0.0.1:7001:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=deploy_monitor
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
volumes:
  db_data:
networks:
  backend: